fos_user:
    service:
        mailer: fos_user.mailer.twig_swift

    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"