vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: '%app.path.article_image%'
            upload_destination: '%kernel.project_dir%/public/%app.path.article_image%'